# -*- coding: utf-8 -*-
"""scikit-learn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGsvWxj6c_tU_HwOx9pASuwHagcX1Aee
"""

# %pip install --upgrade scikit-learn==0.23.0

from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression
import pandas as pd

X, y = load_boston(return_X_y=True)

from sklearn.neighbors import KNeighborsRegressor
import matplotlib.pylab as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

# mod = LinearRegression()
mod = KNeighborsRegressor().fit(X, y)

pipe = Pipeline([
    ('scale', StandardScaler()),
    ('model', KNeighborsRegressor(n_neighbors=1))
])
# pipe.get_params()

mod = GridSearchCV(estimator=pipe, param_grid={'model__n_neighbors': [1,2,3,4,5,6,7,8,9,10]}, cv=3)

mod.fit(X, y)
pd.DataFrame(mod.cv_results_)

print(load_boston()['DESCR'])
